// angular/src/app/components/pages/home/table/table.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface IUser {
  id: string,
  name: string,
  email: string,
  active: boolean,
  role: { id: string, name: string }
}

interface IPaginate {
  limit: number,
  page: number,
  total: number
}

const initialSelectedUser = JSON.parse(JSON.stringify({ id: "", name: "", email: "", active: false, role: { id: "", name: "" } }));

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html'
})
export class TableComponent implements OnInit {

  users: IUser[] = [];
  isSelected: boolean = false;
  selectedUser: IUser = initialSelectedUser;
  paginate: IPaginate = { limit: 10, page: 1, total: 0 }

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.fetchUsers();
  }

  async fetchUsers() {
    const skip = this.paginate.page * this.paginate.limit - this.paginate.limit;
    const response = await this.http.get<any>(`https://dummyjson.com/users?limit=${this.paginate.limit}&skip=${skip}`).toPromise();

    this.users = response.users.map((user: any, index: number) => {
      return {
        id: user.id,
        name: user.firstName + " " + user.lastName,
        email: user.email,
        active: true,
        role: { id: 2, name: "customer" }
      }
    });

    this.paginate.total = response.total;
  }

  nextPage() {
    const total_pages = this.paginate.total / this.paginate.limit;
    if (this.paginate.page < total_pages) {
      this.paginate.page += 1;
      this.fetchUsers();
    }
  }

  previouslyPage() {
    if (this.paginate.page > 1) {
      this.paginate.page -= 1;
      this.fetchUsers();
    }
  }

  selectUser(user: IUser) {
    this.selectedUser = user;
    this.isSelected = true;
  }

  onCloseEditModal() {
    this.isSelected = false;
    this.selectedUser = initialSelectedUser;
  }

  // Other

  existsUsers() {
    return this.users.length > 0;
  }

}

<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
        <!-- Start coding here -->
        <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                <div class="w-full md:w-1/2">
                    <form class="flex items-center">
                        <label for="simple-search" class="sr-only">Search</label>
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400"
                                    fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                        clip-rule="evenodd" />
                                </svg>
                            </div>
                            <input type="text" id="simple-search"
                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-red-500 focus:border-red-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-red-500 dark:focus:border-red-500"
                                placeholder="Search user by ID">
                        </div>
                    </form>
                </div>
                <div
                    class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                    <!-- Create user modal -->
                    <app-create></app-create>
                    <!-- Update user modal -->
                    <app-edit [user]="selectedUser" [canOpen]="isSelected" (close)="onCloseEditModal()"></app-edit>
                </div>
            </div>
            <div class="overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-3">ID</th>
                            <th scope="col" class="px-4 py-3">Name</th>
                            <th scope="col" class="px-4 py-3">Email</th>
                            <th scope="col" class="px-4 py-3">Active</th>
                            <th scope="col" class="px-4 py-3">Role</th>
                            <th scope="col" class="px-4 py-3 text-right"></th>
                        </tr>
                    </thead>
                    <tbody *ngIf="existsUsers()">

                        <tr *ngFor="let user of users; index as i" class="border-b dark:border-gray-700">
                            <th scope="row"
                                class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ user.id }}
                            </th>
                            <td class="px-4 py-3">{{ user.name }}</td>
                            <td class="px-4 py-3">{{ user.email }}</td>
                            <td class="px-4 py-3">{{ user.active }}</td>
                            <td class="px-4 py-3">{{ user.role.name }}</td>
                            <td class="px-4 py-3 flex items-center justify-end">
                                <button (click)="selectUser(user)" type="button"
                                    class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-2 py-1 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                                    </svg>
                                </button>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4"
                aria-label="Table navigation">
                <ul class="inline-flex items-stretch -space-x-px">
                    <li (click)="previouslyPage()"
                        class="flex items-center justify-center h-full py-1.5 px-3 ml-0 cursor-pointer text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-red-400">
                        <span class="sr-only">Previous</span>
                        <svg class="w-5 h-5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </li>
                    <li
                        class="flex items-center justify-center text-sm py-1 px-3 leading-tight cursor-pointer text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-red-400">
                        {{ paginate.page }}
                    </li>
                    <li (click)="nextPage()"
                        class="flex items-center justify-center h-full py-1.5 px-3 leading-tight cursor-pointer text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-red-400">
                        <span class="sr-only">Next</span>
                        <svg class="w-5 h-5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</section>

// vue/src/views/Table.vue
<template>
    <component :is="$route.meta.layout">
        <div class='w-full h-full shadow rounded-md'>
            <div class="relative overflow-x-auto sm:rounded-lg">

                <div class="pb-4 bg-white dark:bg-gray-900 p-5">
                    <label for="table-search" class="sr-only">Search</label>
                    <div class="relative mt-1">
                        <input type="text" id="table-search" v-model="paginate.search" v-on:keydown.enter="handleFetchData"
                            class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Search for items by ID">
                    </div>
                </div>

                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                                Identifier
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Name
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Username
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Email
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Password
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Use :key to track each node's identity, like as React -->
                        <tr v-for="user in users" class="bg-white border-b dark:bg-gray-900 dark:border-gray-700"
                            :key="user.id">
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ user.id }}
                            </th>
                            <td class="px-6 py-4">
                                {{ user.firstName }}
                            </td>
                            <td class="px-6 py-4">
                                {{ user.username }}
                            </td>
                            <td class="px-6 py-4">
                                {{ user.email }}
                            </td>
                            <td class="px-6 py-4">
                                {{ user.password }}
                            </td>
                            <td class="px-6 py-4 flex">
                                <!-- https://vuejs.org/guide/components/props.html#prop-passing-details  -->
                                <div class="mr-2">
                                    <span
                                        class="font-medium text-blue-600 dark:text-blue-500 hover:underline cursor-pointer"
                                        @click="handleSelection({ op: 'update', user: user })">Edit</span>
                                </div>
                                <div>
                                    <span
                                        class="font-medium text-blue-600 dark:text-blue-500 hover:underline cursor-pointer"
                                        @click="handleSelection({ op: 'delete', user: user })">Delete</span>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <nav class="flex justify-end p-5" aria-label="Table navigation">
                    <ul class="inline-flex items-center -space-x-px">
                        <li @click="handlePrevPage">
                            <span href="#"
                                class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                                <span class="sr-only">Previous</span>
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                        clip-rule="evenodd"></path>
                                </svg>
                            </span>
                        </li>
                        <li>
                            <span href="#"
                                class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                                {{ paginate.page }}</span>
                        </li>
                        <li @click="handleNextPage">
                            <span href="#"
                                class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                                <span class="sr-only">Next</span>
                                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                        clip-rule="evenodd"></path>
                                </svg>
                            </span>
                        </li>
                    </ul>
                </nav>

                <TransitionRoot as="template" :show="selected.op === 'update'">
                    <EditUser :identifier="selected.user.id" :username="selected.user.username"
                        :firstName="selected.user.firstName" :email="selected.user.email" :password="selected.user.password"
                        @close="handleCloseModal" />
                </TransitionRoot>

                <TransitionRoot as="template" :show="selected.op === 'delete'">
                    <DeleteUser @close="handleCloseModal" :identifier="selected.user.id" />
                </TransitionRoot>
            </div>
        </div>
    </component>
</template>

<script setup>
import * as Vue from 'vue';
import { TransitionRoot } from '@headlessui/vue';
import EditUser from '../components/formulary/users/EditUser.vue';
import DeleteUser from '../components/formulary/users/DeleteUser.vue';
import axios from 'axios';

const initialUsers = [];
const initialPaginate = JSON.stringify({ limit: 10, page: 1, search: "" });
const initialSelected = JSON.stringify({ op: 'none', user: {} });

const users = Vue.ref([]);
const paginate = Vue.reactive(JSON.parse(initialPaginate));
const selected = Vue.reactive(JSON.parse(initialSelected));

Vue.onMounted(async () => {
    Object.assign(paginate, JSON.parse(initialPaginate));
    users.value = initialUsers;
    handleFetchData();
});

async function handleFetchData() {
    try {

        const offset = paginate.page * paginate.limit - paginate.limit;

        const response = axios.get(`https://dummyjson.com/users/${paginate.search}?limit=${paginate.limit}&skip=${offset}&select=id,email,firstName,username,password,image`);
        users.value = (await response).data.users;

    } catch (e) {
        console.log(e);
    }
}

function handleNextPage() {
    // If actual page is not the last page
    if (paginate.page < 100 / paginate.limit) { //  Math.round() if result is not an integer
        Object.assign(paginate, {
            ...paginate,
            ["page"]: paginate.page + 1
        });
    }
    handleFetchData();
}

function handlePrevPage() {
    // Is the actual page is not the first one
    if (paginate.page > 1) {
        Object.assign(paginate, {
            ...paginate,
            ["page"]: paginate.page - 1
        });
    }
    handleFetchData();
}

function handleSelection(selection) {
    Object.assign(selected, selection);
}

function handleCloseModal() {
    Object.assign(selected, JSON.parse(initialSelected));
}

</script>
