// react/2-ssr-next/pages/login/index.js

import * as React from 'react';
import Link from 'next/link';
import { useForm } from "react-hook-form";
import * as yup from "yup";
import { yupResolver } from '@hookform/resolvers/yup';

const schema = yup.object({
  email: yup.string().email().required("Email is required"),
  password: yup.string().required("Password is required")
}).required();

export default function Home() {

  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(schema)
  });

  function handleLogin(data) {
    console.log(data)
  }

  return (
    <section class="bg-gray-50">
      <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <Link href="login" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 ">
          <img class="w-8 h-8 mr-2 " src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" alt="logo" />
          <img class="w-8 h-8 mr-2 " src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" alt="logo" />
          NextJS
        </Link>
        <div
          class="w-full bg-white rounded-lg dark:border md:mt-0 sm:max-w-md xl:p-0 shadow-lg"
        >
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
              Sign in to your account
            </h1>
            <form class="space-y-4 md:space-y-6"
              onSubmit={handleSubmit(handleLogin)}
            >
              <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Your email</label>
                <input type="email" name="email" id="email" {...register('email', { required: true, maxLength: 255, pattern: /^\S+@\S+\.\S+$/ })} className={`bg-gray-50 border ${errors.email ? 'border-red-300' : 'border-gray-300'} text-gray-900 sm:text-sm rounded-lg focus:ring-sky-600 focus:border-sky-600 block w-full p-2.5 dark:focus:ring-blue-500 dark:focus:border-blue-500`} placeholder="name@company.com" required="" />
                {errors.email && <span className='text-sm text-red-300'>{errors.email.message}</span>}
              </div>
              <div>
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900">Password</label>
                <input type="password" name="password" id="password" {...register('password', { required: true, min: 10, maxLength: 255 })} placeholder="••••••••" className={`bg-gray-50 border ${errors.password ? 'border-red-300' : 'border-gray-300'} text-gray-900 sm:text-sm rounded-lg focus:ring-sky-600 focus:border-sky-600 block w-full p-2.5 dark:focus:ring-blue-500 dark:focus:border-blue-500`} required="" />
                {errors.password && <span className='text-sm text-red-300'>{errors.password.message}</span>}
              </div>
              <div class="flex items-center justify-between">
              </div>
              <button type="submit" class="w-full text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-sky-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800">Sign in</button>
              <p class="text-sm font-light text-gray-400">
                Don’t have an account yet? <Link href="registration" class="font-medium text-sky-600 hover:underline dark:text-sky-500">Sign up</Link>
              </p>
            </form>
          </div>
        </div>
      </div>
    </section>
  )
}

// vue/src/pages/Login.vue
<template>
    <div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="w-full max-w-md space-y-8">
            <div>
                <div class="flex">
                    <img class="mx-auto h-12 w-auto"
                        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" />
                </div>
                <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign in to your account</h2>
            </div>
            <form class="mt-8 space-y-6" v-on:onSubmit="handleSubmit">
                <input type="hidden" name="remember" value="true" />

                <div class="-space-y-px rounded-md shadow-sm">
                    <div class="mb-8">
                        <label for="email-address" class="sr-only">Email address</label>
                        <input id="email-address" name="email" type="email" v-model="form.email"
                            class="relative block w-full rounded border-0 p-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-1 focus:ring-inset focus:ring-emerald-400 sm:text-sm sm:leading-6"
                            placeholder="Email address" />
                        <span className='text-red-500 text-sm'>{{ formError.email.message }}</span>
                    </div>
                    <div>
                        <label for="password" class="sr-only">Password</label>
                        <input id="password" name="password" type="password" v-model="form.password"
                            class="relative block w-full rounded border-0 p-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-1 focus:ring-inset focus:ring-emerald-400 sm:text-sm sm:leading-6"
                            placeholder="Password" />
                        <span className='text-red-500 text-sm'>{{ formError.password.password }}</span>
                    </div>
                </div>

                <div class="flex items-center justify-between">
                    <div class="flex items-center">
                        <input id="remember-me" name="remember-me" type="checkbox" v-model="rememberMe"
                            class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" />
                        <label for="remember-me" class="ml-2 block text-sm text-gray-900">Remember me</label>
                    </div>
                </div>

                <div>
                    <button type="submit"
                        class="group relative flex w-full justify-center rounded-md bg-emerald-600 py-2 px-3 text-sm font-semibold text-white hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">
                        Sign in
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
  
<script setup>
import { reactive, ref } from 'vue';

const form = reactive({ email: "", password: "" });
const formError = reactive({ email: { error: false, message: "" }, password: { error: false, message: "" } });
const rememberMe = ref(false);

function handleSubmit(e) {
    e.preventDefault();
    console.log(form);
    console.log(rememberMe.value)
}

</script>
